# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nebari-dia-content-library',
                'doc_host': 'https://equinor.github.io',
                'git_url': 'https://github.com/equinor/nebari-dia-content-library',
                'lib_path': 'nebari_dia_content_library'},
  'syms': { 'nebari_dia_content_library.component-library': { 'nebari_dia_content_library.component-library.get_rigs': ( 'contentlibrary.html#get_rigs',
                                                                                                                         'nebari_dia_content_library/component-library.py'),
                                                              'nebari_dia_content_library.component-library.get_wellbores': ( 'contentlibrary.html#get_wellbores',
                                                                                                                              'nebari_dia_content_library/component-library.py')}}}
