# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/ContentLibrary.ipynb.

# %% auto 0
__all__ = ['all_dates_dd', 'rigs_query', 'rigs_options', 'all_rigs_dd', 'wellbores_query', 'wellbore_options', 'all_wellbores_dd',
           'df_sensors', 'all_sensors_dd', 'dates_dd', 'rigs_dd', 'wellbore_dd', 'get_rigs', 'get_wellbores']

# %% ../nbs/ContentLibrary.ipynb 2
import panel as pn
import panel_material_ui as pmui
from datetime import date, timedelta
import nebari_dia_adx.gremlin_connection as gc
import nebari_dia_adx.adx_connection as nbx
pn.extension()

# %% ../nbs/ContentLibrary.ipynb 6
all_dates_dd = pmui.DatetimePicker()

# let's call the dropdown in order to visualize it:
all_dates_dd

# %% ../nbs/ContentLibrary.ipynb 8
rigs_query = f"""g.V().hasLabel('rigs')
                    .group()
                    .by(values('rigName'))
                    .by(values('id'))
                .unfold()  
                .order()
                    .by(select(keys).unfold())  
                .group()
                    .by(select(keys))  
                    .by(select(values))"""

rigs_options = gc.submit_query(rigs_query)[0]

all_rigs_dd = pmui.Select(options=rigs_options, searchable=True)

#  let's call the dropdown in order to visualize it:
pn.Row(all_rigs_dd, height=300)

# %% ../nbs/ContentLibrary.ipynb 10
# wellbores_query = f"""g.V().hasLabel('wellbores').valueMap('wellboreClassification', 'wellboreName', 'wellboreId', 'wellboreType','wellboreStatus' )"""
wellbores_query = f"""g.V().hasLabel('wellbores')
                    .group()
                    .by(values('wellboreName'))
                    .by(values('id'))
                .unfold()  
                .order()
                    .by(select(keys).unfold())  
                .group()
                    .by(select(keys))  
                    .by(select(values))"""
# wellbores_query = f"""g.V().hasLabel('wellbores')
                
#                     .order()
#                         .by(values('wellboreName'))  
#                      .group()
#                          .by(values('wellboreName'))
#                          .by(values('id'))
#                     """
wellbore_options = gc.submit_query(wellbores_query)[0]
# wellbore_options

# %% ../nbs/ContentLibrary.ipynb 11
all_wellbores_dd = pmui.Select(options=wellbore_options, searchable=True)

#  let's call the dropdown in order to visualize it:
pn.Row(all_wellbores_dd, height=300)

# %% ../nbs/ContentLibrary.ipynb 13
df_sensors = nbx.perform_query(f'''
TimeSeriesColumnsView ''', database= "Sensor Timeseries", table = 'TimeSeriesColumnsView' )

all_sensors_dd = pmui.Select(name='Sensors', options=dict(zip(df_sensors['FinalColumnValue'], df_sensors['ColumnName'])), searchable=True )


#  let's call the dropdown in order to visualize it:
pn.Row(all_sensors_dd, height=300)

# %% ../nbs/ContentLibrary.ipynb 16
dates_dd = pmui.DatetimePicker(value = date.today() - timedelta(days=1)) 

#  let's call the dropdown in order to visualize it:
pn.Row(dates_dd, height=300)

# %% ../nbs/ContentLibrary.ipynb 18
def get_rigs(chosenDate = date.today() - timedelta(days=1) , end_date = None):
    end_date = (chosenDate + timedelta(days=1)).strftime("%Y-%m-%dT%H:%M:%SZ") if end_date is None else end_date
    print(end_date)
    rigs_query = f"""
        g.V().hasLabel('operations')
            .has('startTimeUTC', gt('{chosenDate}')).has('endTimeUTC', lt('{end_date}'))
            .in('PERFORMED')
            .group()
                .by(values('properties', 'rigName'))
                .by(values('id'))
            .unfold()  
            .order()
                .by(select(keys).unfold())  
            .group()
                .by(select(keys))  
                .by(select(values))
        """
    return gc.submit_query(rigs_query)[0]



rigs_dd = pmui.Select(options=pn.bind(gc.get_rigs, dates_dd.param.value), searchable=True)

#  let's call the dropdown in order to visualize it:
pn.Row(rigs_dd, height=300)

# %% ../nbs/ContentLibrary.ipynb 21
def get_wellbores(rig, chosenDate = date.today() - timedelta(days=1) , end_date = None):
    end_date = (chosenDate + timedelta(days=1)).strftime("%Y-%m-%dT%H:%M:%SZ") if end_date is None else end_date
    wellbores_query =  f"""g.V('{rig}')
                    .out('PERFORMED').has('startTimeUTC', gt('{dates_dd.value}')).has('endTimeUTC',lt('{end_date}'))
                    .out('ON')
                       .group().by(values('properties', 'wellboreName')).by(values('id'))
                       .unfold()  
                        .order()
                            .by(select(keys).unfold())  
                        .group()
                            .by(select(keys))  
                            .by(select(values))
                    """
    return gc.submit_query(wellbores_query)[0]



wellbore_dd = pmui.Select(options=pn.bind(get_wellbores, rigs_dd.param.value, dates_dd.param.value), searchable=True)

#  let's call the dropdown in order to visualize it:
pn.Row(wellbore_dd, height=300)

# %% ../nbs/ContentLibrary.ipynb 23
df_sensors = nbx.perform_query(f'''
TimeSeriesColumnsView ''', database= "Sensor Timeseries", table = 'TimeSeriesColumnsView' )

all_sensors_dd = pmui.Select(name='Sensors', options=dict(zip(df_sensors['FinalColumnValue'], df_sensors['ColumnName'])), searchable=True )


#  let's call the dropdown in order to visualize it:
pn.Row(all_sensors_dd, height=300)
